### ISSUE TITLE
Fedora -RPM

### ISSUE THREAD

**Issue by LastNeoN** [aymanbagabas/Huawei-WMI#18]
sudo rpm -i huawei-wmi-3.2-1dkms.noarch.rpm
Loading new huawei-wmi-3.2 DKMS files...
Building for 5.2.7-200.fc30.x86_64
Module build for kernel 5.2.7-200.fc30.x86_64 was skipped since the
kernel headers for this kernel does not seem to be installed.
___________________________________________________

Последняя проверка окончания срока действия метаданных: 0:31:34 назад, Сб 17 авг 2019 08:45:00.
Пакет kernel-headers-5.2.8-200.fc30.x86_64 уже установлен.
Зависимости разрешены.
Отсутствуют действия для выполнения
Выполнено!

**Comment by aymanbagabas** [comment]
> sudo rpm -i huawei-wmi-3.2-1dkms.noarch.rpm
> Loading new huawei-wmi-3.2 DKMS files...
> Building for 5.2.7-200.fc30.x86_64
> Module build for kernel 5.2.7-200.fc30.x86_64 was skipped since the
> kernel headers for this kernel does not seem to be installed.

Seems like you're missing kernel headers. `sudo dnf install kernel-headers kernel-devel`
