### ISSUE TITLE
Only the Developing Version (>3.2) works for HUAWEI Matebook 14 (KLV-WX9)

### ISSUE THREAD

**Issue by wiliamwalace** [aymanbagabas/Huawei-WMI#22]
**Is your feature request related to a problem? Please describe.**

I have openSUSE Tumbleweed with kernel 5.3.2 running on my Matebook 14 (KLV-WX9). A Huawei-WMI driver is shipped with the kernel that enables the Fn keys (Thanks a lot!). But there is still frustrations that the directory for battery protection `/sys/devices/platform/huawei-wmi` never existed and the micmute LED was always off. The driver shipped with the kernel is no older than v3.2 (as I was informed when trying to build the latest release (v3.2) from this repo to replace it).

**Describe the solution you'd like**

Fortunately the developing version from the Master branch saves me. Since there is no discussion about Matebook 14 here, I would like to make this note for the users of this mode. And hopefully the developing version would soon mature to form a release. 

Thanks again for the efforts of the author and all the contributors.

**Comment by aymanbagabas** [comment]
The driver's version that is shipped with the kernel is version `v2.0` which doesn't have battery protection, micmute led, and other features.

The new changes finally got accepted in the upcoming kernel release, you should expect to see these changes shipped with the kernel soon. [Link](https://patchwork.kernel.org/project/platform-driver-x86/list/?series=177803&archive=both&state=*)
