### ISSUE TITLE
I cannot run Matebook applet

### ISSUE THREAD

**Issue by edoardomazzella** [aymanbagabas/Huawei-WMI#26]
Hi,
i downloaded and installed Huawei-WMI and all the stuff seems to work. However i do not see the matebook applet available.
In the README.md of matebook-applet repo the following sentences are written:
"Starting with version 1.2 the best way to get the matebook-applet working is to install Huawei-WMI driver by Ayman Bagabas."
"After installing the driver you may start using the matebook-applet right away."
Is there something else to do in order to install the matebook-applet?
Thank you.

**Comment by nekr0z** [comment]
> Is there something else to do in order to install the matebook-applet?

Yes, you need to download/install `matebook-applet` itself. :)

That sentence you've quoted basically means there's no need for additional setup: you just install the driver, install matebook-applet, and there you go, no need to tweak up the system and get your hands dirty. I might need to rephrase that to make it more clear.

**Comment by edoardomazzella** [comment]
thank you

**Comment by aymanbagabas** [comment]
Can you please try v3.4 and provide a dmesg log?

**Comment by edoardomazzella** [comment]
Hi, currently I uninstalled linux on my pc, i'll try as soon as possible.
