### ISSUE TITLE
What's the meaning of start_threshold?

### ISSUE THREAD

**Issue by lolilolicon** [aymanbagabas/Huawei-WMI#37]
First, thanks very much for implementing the battery protection feature. I can
confirm that it works on MateBook-14 ("Product": KLV-WX9). Well, at least the
end_threshold part, which happily prevents the battery from getting near 100%.

However, I'm confused what the start_threshold means. For, with the AC plugged
in, the battery gets charged up to the end_threshold, regardless of start_threshold.

Some sources, including issue #35, suggest if the battery capacity (charge
level) is between the start & end thresholds, the AC should not charge the
battery, or more precisely, the battery capacity should stay unchanged. This,
as stated above, is not true in my case.

Moreover, this, would mean that to turn off battery protection the thresholds
should be set to "100 100" instead of "0 100", since "0 100" would mean, "Hey,
AC, always just keep the battery capacity where it's at." Yet "0 100" is what I see
used in scripts (e.g. `batpro`) for turning battery protection off. Confused I am.
I notice the "factory" values are "0 0", which, strangely, cannot be written to the
file `/sys/devices/platform/huawei-wmi/charge_control_thresholds`, yet do not
raise the error `write error: Invalid argument` like, say, "100 100", but fail silently.
But isn't it more logical to accept "0 0" and make it mean, as it surely already
does, "turn off battery protection"?

Edit: Oh, there's another difference from the description in #35. When the AC is
plugged in, if the battery capacity is **above** end_threshold, the battery status will
be "Discharging" instead of "Unknown", and the battery will actually **discharge**
as if the AC is not plugged in at all, until it lowers to end_threshold, that is.

**Comment by aymanbagabas** [comment]
Closing...

**Comment by mklemm2** [comment]
The question is still unanswered. I also don't get the meaning of start_threshold, it seems to make no difference in behavior at all.
