### ISSUE TITLE
Is there any support for brightness adjustment?

### ISSUE THREAD

**Issue by ZerdoX-x** [aymanbagabas/Huawei-WMI#41]
It would be really cool if Fn+F1 and Fn+F2 would work the same as Fn+F5, Fn+F6, Fn+F7 (adjust volume, mute mic)

**Comment by nekr0z** [comment]
On MateBook 13 `WRT-W19` they do work.

**Comment by ZerdoX-x** [comment]
@nekr0z I can't get it work on HN-W19R (AMD R5 3500U 2020)

**Comment by aymanbagabas** [comment]
What DE are you running? Major DEs have their own implementation to handle ACPI events.

**Comment by ZerdoX-x** [comment]
@aymanbagabas I use i3
