### ISSUE TITLE
Some of the function hotkeys not work in TTYs

### ISSUE THREAD

**Issue by pur2evil** [aymanbagabas/Huawei-WMI#47]
For the record, all of the hotkeys, they do work perfectly in Desktop Environments.
However, some function hotkeys like Volume Up/Down, Mute… they just don't work in TTYs.
I'm not sure if this is a bug. Or the driver is for Desktop only?
Help needed.

**Comment by aymanbagabas** [comment]
Most of the hotkeys work through firing ACPI events, a desktop environment like GNOME or KDE implements their own ACPI handler. You could try [acpid](https://wiki.archlinux.org/index.php/acpid) if you want to have your own handler that _should_ work outside of a desktop environment.

**Comment by pur2evil** [comment]
Yea, acpid. That was my Plan B.
I will try it when I got time.
Thanks man. You are awesome.
