### ISSUE TITLE
Can't run make command

### ISSUE THREAD

**Issue by lenngro** [aymanbagabas/Huawei-WMI#5]
Hi,
I have the following problem when running the `make` command:

```
arch/x86/Makefile:150: CONFIG_X86_X32 enabled but no binutils support
arch/x86/Makefile:227: *** You are building kernel with non-retpoline compiler, please update your compiler..  
```
I'm running Manjaro with the 4.19 Linux Kernel.
Is there any requirement to the linux kernel used?

**Comment by aymanbagabas** [comment]
> Hi,
> I have the following problem when running the `make` command:
> 
> ```
> arch/x86/Makefile:150: CONFIG_X86_X32 enabled but no binutils support
> arch/x86/Makefile:227: *** You are building kernel with non-retpoline compiler, please update your compiler..  
> ```
> I'm running Manjaro with the 4.19 Linux Kernel.
> Is there any requirement to the linux kernel used?

Hmm.. It's complaining about `binutils`. Try to install it and see what happens. `pacman -S binutils`
There is no requirements, this should work with any recent version.

**Comment by lenngro** [comment]
I was missing the `sudo` before `make` . Sometimes it's the little things.
After running `sudo make` and `sudo make install` afterwards + reboot the hotkeys are working.
Thank you so much for this awesome driver!
