### ISSUE TITLE
Donate does not work

### ISSUE THREAD

**Issue by m1khal3v** [aymanbagabas/Huawei-WMI#54]
**Describe the bug**
When I try to donate on buymeacoffee, I get an error

```
This account cannot currently make live charges.
If you are a customer trying to make a purchase, please contact the owner of this site.
Your transaction has not been processed.
```

**Comment by aymanbagabas** [comment]
@m1khal3v thank you for reporting this issue. I've fixed the problem which turned out to be an issue with Stripe. Anyway, I tested it on my end and it now seems to work just fine. Thank you again for your support!

**Comment by m1khal3v** [comment]
@aymanbagabas It works now. Thank you for your great work
