### ISSUE TITLE
keyboard backlight timeout option "never"

### ISSUE THREAD

**Issue by www159** [aymanbagabas/Huawei-WMI#71]
Hi, I have install branch feat/kbdlight and it works fine on my laptop.
backlight timeout can be easily set but I wonder if I can set the backlight never turning off?

There is the Huawei  F&Q show![huawei implenment](https://consumer-tkbdownload.huawei.com/ctkbfm/servlet/download/downloadServlet/H4sIAAAAAAAAAD2QS0_DMBCE_4vPBa1fuw4nYidRuSAO5VyZ2gmW2rTKAwSI_04cRexttKOZT_PD5jEOh69bZA-Msx0L189-k3KRbTrHZ3_JMvZ383hMF9_FI6zHuVFCcAJxf-u7zf3ip_fsBmh1REVIpDBwHwoTicDo0J6KmKve0vdTWKz78nHN5poQJcLyOg3RT-naH1Ku5giFkqCAL6U7Nqau99M8ZCgojNRVJUpbV4rIuAbQVgjKkJVopGkUOSfQolNaSCF0zaEmISw0DbqM8eHPKbz-rzANc1zZthX2Jfv9AypAzZkmAQAA.png)

and I have reviewed the related issues. Is there something like `timeout-toggle` to implenment the function?

**Comment by sermart1234** [comment]
`echo 0 | sudo tee /sys/devices/platform/huawei-wmi/kbdlight_timeout`

**Comment by Alexey336** [comment]
> `echo 0 | sudo tee /sys/devices/platform/huawei-wmi/kbdlight_timeout`

For me there is no such file. Do I need to build newer driver from source? I have this feature on windows

**Comment by sermart1234** [comment]
@Alexey336 build branch https://github.com/aymanbagabas/Huawei-WMI/tree/feat/kbdlight

**Comment by Alexey336** [comment]
> @Alexey336 build branch https://github.com/aymanbagabas/Huawei-WMI/tree/feat/kbdlight

Still have no such file

**Comment by sermart1234** [comment]
Please, send acpidump and dmidecode output
